name: Create Release Branch

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'リリースバージョン (例: 1.0.0)'
        required: false
        type: string

jobs:
  create-release-branch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      release_branch: ${{ steps.set-release-version.outputs.release_branch }}
      release_version: ${{ steps.set-release-version.outputs.release_version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: develop

      - name: Set release version
        id: set-release-version
        run: |
          # バージョンを取得（指定がない場合は自動生成）
          if [ -z "${{ github.event.inputs.version }}" ]; then
            # version.txtが存在しない場合は初期値を使用
            if [ ! -f version.txt ]; then
              echo "1.0.0" > version.txt
            fi

            # 現在のバージョンを読み取り
            CURRENT_VERSION=$(cat version.txt)

            # セマンティックバージョニングに基づいて更新
            # 例: 1.0.0 -> 1.0.1
            IFS='.' read -r -a version_parts <<< "$CURRENT_VERSION"
            MAJOR="${version_parts[0]}"
            MINOR="${version_parts[1]}"
            PATCH=$((version_parts[2] + 1))
            RELEASE_VERSION="$MAJOR.$MINOR.$PATCH"
          else
            RELEASE_VERSION="${{ github.event.inputs.version }}"
          fi

          RELEASE_BRANCH="release/v${RELEASE_VERSION}"

          # 出力を設定
          echo "release_branch=$RELEASE_BRANCH" >> $GITHUB_OUTPUT
          echo "release_version=$RELEASE_VERSION" >> $GITHUB_OUTPUT

      - name: Update version.txt
        run: |
          # バージョンを更新
          echo "${{ steps.set-release-version.outputs.release_version }}" > version.txt

      - name: Create Pull Request to main
        uses: peter-evans/create-pull-request@v7
        with:
          title: "Release branch for ${{ steps.set-release-version.outputs.release_version }}"
          body: |
            This PR creates a new release branch from develop.
            Please review and merge this PR to create the release branch.
          branch: ${{ steps.set-release-version.outputs.release_branch }}
          base: main
          commit-message: "chore: update version to ${{ steps.set-release-version.outputs.release_version }}"
