name: Create Release Branch

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'リリースバージョン (例: 1.0.0)'
        required: false
        type: string

jobs:
  create-release-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'

      - name: Create release branch
        run: |
          # バージョンを取得（指定がない場合は自動生成）
          if [ -z "${{ github.event.inputs.version }}" ]; then
            # version.txtが存在しない場合は初期値を使用
            if [ ! -f version.txt ]; then
              echo "1.0.0" > version.txt
            fi

            # 現在のバージョンを読み取り
            CURRENT_VERSION=$(cat version.txt)

            # セマンティックバージョニングに基づいて更新
            # 例: 1.0.0 -> 1.1.0
            IFS='.' read -r -a version_parts <<< "$CURRENT_VERSION"
            MAJOR="${version_parts[0]}"
            MINOR=$((version_parts[1] + 1))
            PATCH="0"
            RELEASE_VERSION="$MAJOR.$MINOR.$PATCH"
          else
            RELEASE_VERSION="${{ github.event.inputs.version }}"
          fi

          RELEASE_BRANCH="release/v${RELEASE_VERSION}"
          
          # developブランチから新しいreleaseブランチを作成
          git checkout -b $RELEASE_BRANCH
          git push origin $RELEASE_BRANCH

      - name: Update version.txt
        run: |
          # バージョンを更新
          echo "$RELEASE_VERSION" > version.txt

          # 変更をコミットしてプッシュ
          git add version.txt
          git commit -m "chore: update version to $RELEASE_VERSION"
          git push origin $RELEASE_BRANCH

      - name: Create Pull Request to main
        uses: peter-evans/create-pull-request@v6
        with:
          title: "Release branch for $RELEASE_VERSION"
          body: |
            This PR creates a new release branch from develop.
            Please review and merge this PR to create the release branch.
          branch: ${{ env.RELEASE_BRANCH }}
          base: main

      - name: Create Pull Request to develop
        uses: peter-evans/create-pull-request@v6
        with:
          title: "Release branch for $RELEASE_VERSION"
          body: |
            This PR creates a new release branch from develop.
            Please review and merge this PR to create the release branch.
          branch: ${{ env.RELEASE_BRANCH }}
          base: develop
